language: node_js
node_js:
- '8'
deploy:
  provider: npm
  email: supersnager@gmail.com
  api_key:
    secure: bpccApe1VszG+uSocza9jjCRYZCreY9ajS0Noh0gIVNqrzrrSow9GiPoYpdSw3Af+e1AxJ15MuFVq2YmwuNiySNlvZGzrdTqjK+Zps3JF+XXsWGhi0fzjNzh0p+RbgOHKXZkahPLS1pca3XTuZ9XeQp2eEpUHBymOufvtBsIwIIdgrOUpJ4bV9YqcnS5NMwRPF17Qju3sLJPFY6YQGls4/Tdw/VKDrL2dgz7j/7oK2rFZtOaA9T+HM7m/xxT81YHIPKJQ+HIau0McpR7MffuWBp0a3viWk6Qq8oXTghAM17v8CkeElQuBwDc+nlR2KVWJ3/6EMThTE+H+OMdsHRWMyAtVLWf2LYrrUBHIU2urmMN+bmls5ks0xfzGACYD9y0CkEJf51iWn0KxXgDa1Lqqw0yZ0+odgZoRR6Lt9CdWclSjSb3X6Nx49L+4YXkrUOLtrpRrOc+/RIVNuDmLv9Fu2sM+XxdvBSqBd8fcGgnd6MK/CmqJolLPxkPTVHkPUdQrwM9TdF3b89nk0JxQm1MK/zPD3ASDHgvddmFfgltgpFWOqS8VeSPzC1fSAoIBzLGDVw/igDKD7f4v+naaGjTAkPKb9OaQuu6ldyyppY8cPJF+7UXZmes16P0mtQXKc/nFtyhEMGFw5d8LlOqxkBJvEZdzvs4WtECl4bYSWPjUeQ=
  skip_cleanup: true
  on:
    tags: true
    branch: master
