language: node_js
node_js:
  - "8"
deploy:
  provider: npm
  email: "supersnager@gmail.com"
  api_key: "PjeAaSfrIMV81BJrgupOfMzoYaBUElYhksb0E8Xq5cqrnNFhvS9lVCsO2g1/E33FKo7EX84965PtgK2TduHbuVhSSTYTOnd4AVeal8FvUH9nwqesUxX7CplY0eD8+gdI4L5TQuqjUX2+x7BK5JEGdGQBhoymgxxeOevJTq6ySmYql2pDmr8cZGQQKS6IgceqyWB3cvuIpLEza7ir5h8Xt3y+vI4IEouLjIdHvI3csPxL9hED91+H3Mf+VTQ4BEBvg8w5wBBaOSqLPco6shqmTOTATbioRHvSDWCvTTPPpwjhdoduQYM174F5Ov2Y0n8XWNBC6Z4Vnd77tny7ZDue5uQp00mpwM5J/jJXu6VCKkrfoNNBxM+sd5DFbQuGn/DLJMYcMusf7XpXpAbT9yuXhaSi1HkVH7M1FUJKxaca3BZB3IJGHLCfhrcEWMPGNkvh2Ga5y044XflqWoEGFLfFKF+mV/BD7Z1NAW93xrYvLjQ7ZQCE5pgu91jG1zCaGcZZ5pa0vo0IGdQLmvak2TGZMloFby7xvgPaRs7aGdLzBv2Snno8QefP1rnkxJHH7zbTYS5qQdqYteqoXnyT38fN9ajQm3Uqj5a+bm2IWqpLr4m0GLqmHebTP2i0+wFwkizUe9G8D4TPhBvT+fiVNId2+zutgY4a9HLYEY+fR3T0KHM="
  on:
    tags: true
    branch: release