name: build

on:
  push:
    tags:
      - *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: https://registry.npmjs.org/
          scope: '@adt'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Publish package
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: npm publish
